[sql_server]
driver = ODBC Driver 18 for SQL Server
server = LAPTOP-FPME\SQLEXPRESS
users_database = TheoriaM
session_logs_database = TheorIAM
username = usuario_web
; Generar el valor desde Backend con: python -m services.database_secret
password_encrypted = DPAPI:AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAAGT5uQS7zcUK/TVIdDb2yCAAAAAA6AAAAVABoAGUAbwByAGkAYQBNACAAUwBRAEwAIABTAGUAcgB2AGUAcgAgAHAAYQBzAHMAdwBvAHIAZAAAABBmAAAAAQAAIAAAAFcuNP0j4e+JNF1vrB9AzoPfOhp+nVyGom8Ye5804aeeAAAAAA6AAAAAAgAAIAAAAJC8NkWbJhh7szkgF+kAFiYORil76tBatyHhN/mEwx4XEAAAAIsSOP5gb6w7RJwAThWe9wFAAAAA0/20agjb4rDq+3H1vgPbJ/vPE7jeiMV0EvyNP2EF2Ujx0uNvSLoGSH6Jn7mvtFgeWJDvv3M69fSXAy4EDiMbfg==
password_environment_variable = THEORIAM_DB_PASSWORD
encrypt = no
trust_server_certificate = no
pooling = no
multiple_active_result_sets = no
application_name = TheoriaM
connection_timeout_seconds = 15
command_timeout_seconds = 0
account_status = activo
